# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/development/cicd/templates/
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

linting:
  image: ghcr.io/karpatkey/pylint310
  script:
    - |
      set -o pipefail
      STATUS=0
      echo "Linting the script"
      echo "Runing Black..."
      black --check . || STATUS=1
      echo "Running isort..."
      isort . --check-only || STATUS=1
      echo "Running Flake8..."
      flake8 . || STATUS=1
      exit status
  rules:
    - when: always

unit-testing:
  image: python:3.11
  before_script:
    # Install dependencies
    #- pip install -r requirements.txt
    - pip install pytest
  script:
    - echo "Running unit testing"
    - pytest
